import { ConnectButton } from '@rainbow-me/rainbowkit'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useSigner, useProvider } from 'wagmi'
import { SplitsClient } from '@0xsplits/splits-sdk'

import styles from '../styles/Home.module.css'

const mumbaiChainId = 80001

const Home: NextPage = (test: any) => {
  const { data, error, isLoading, refetch } = useSigner()
  const signer = data
  const provider = useProvider()
  console.log('signer and provider', { signer: data, provider })

  const splitsClient = new SplitsClient({
    chainId: mumbaiChainId,
    provider,
    signer: signer || undefined,
  })

  const args = {
    recipients: [
      {
        address: '0xd439d0FBBB1541083Bc4F4b589724005796AE604',
        percentAllocation: 50.0,
      },
      {
        address: '0xD20103EBaF92296fEFE18Db36A7ce95148Cd666F',
        percentAllocation: 50.0,
      },
    ],
    distributorFeePercent: 1.0,
    controller: '0x6CbC2d39BA905b44a5876FdBf6C053Fa57dfc887',
  }

  const createSplit = async () => {
    if (signer) {
      try {
        const response = await splitsClient.createSplit(args)
        console.log(JSON.stringify(response, null, 2))
        window.alert(response)
      } catch (e: any) {
        window.alert(e)
        console.log('Error', e)
      }
    } else {
      window.alert('Please sign in')
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <button onClick={createSplit}>Create Split</button>

        <h2>Configs I am using</h2>
        <h4>Recepients</h4>
        <p className={styles.configs}>
          {JSON.stringify(args.recipients, null, 2)}
        </p>
        <h4>Controller</h4>
        <p className={styles.configs}>
          {JSON.stringify(args.controller, null, 2)}
        </p>
      </main>
    </div>
  )
}

export default Home
