import { ConnectButton } from '@rainbow-me/rainbowkit'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useSigner, useProvider } from 'wagmi'
import { SplitsClient } from '@0xsplits/splits-sdk'
import { Button, Heading } from '@chakra-ui/react'

import styles from '../styles/Home.module.css'

const mumbaiChainId = 80001

const Home: NextPage = (test: any) => {
  const { data, error, isLoading, refetch } = useSigner()
  const signer = data
  const provider = useProvider()
  console.log('signer and provider', { signer: data, provider })

  const splitsClient = new SplitsClient({
    chainId: mumbaiChainId,
    provider,
    signer: signer || undefined,
  })

  const args = {
    recipients: [
      {
        address: '...recepient add. 1',
        percentAllocation: 50.0,
      },
      {
        address: '...recepient add. 2',
        percentAllocation: 50.0,
      },
    ],
    distributorFeePercent: 1.0,
    controller: '...controller address',
  }

  const createSplit = async () => {
    if (signer) {
      try {
        const response = await splitsClient.createSplit(args)
        window.alert(JSON.stringify(response, null, 2))
        console.log('Response', JSON.stringify(response, null, 2))
      } catch (e: any) {
        window.alert(e)
        console.log('Error', e)
      }
    } else {
      window.alert('Please sign in')
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <ConnectButton />
        </div>
        <div>
          <Button onClick={createSplit}>Create Split</Button>
        </div>
        <div>
          <Heading size="lg" textAlign="center">
            Configs I am using
          </Heading>
          <Heading size="md">Recepients</Heading>
          <p className={styles.configs}>
            {JSON.stringify(args.recipients, null, 2)}
          </p>
          <Heading size="md">Controller</Heading>
          <p className={styles.configs}>
            {JSON.stringify(args.controller, null, 2)}
          </p>
        </div>
      </main>
    </div>
  )
}

export default Home
